const Movies = [
    { 
        Name: 'SQUID GAME',
        Frame: "/MovieCardPosters/1.png", 
        BigPoster: '/BigPosters/Big1.png', 
        Logo: '/MovieLogos/Logo_1.png',
        Context: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
        Release: '2024',
        Category: 'A',
        Type: 'Show',
        Theme_1: 'Thrillers',
        Theme_2: 'Dramas',
        NetflixType: '/NetflixType/N_Series.png',
    },

    { 
        Name: 'DABBA CARTEL',
        Frame: "/MovieCardPosters/2.png", 
        BigPoster: '/BigPosters/Big2.png',
        Logo: '/MovieLogos/Logo_2.png',
        Context: "When an investigation into a pharma company hits close to home, five women launch a tiffin service with a secret ingredient.",
        Release: '2025',
        Category: 'U/A 16+',
        Type: 'Show',
        Theme_1: 'Thrillers',
        Theme_2: 'Dramas',
        NetflixType: '/NetflixType/N_Series.png',
    },

    { 
        Name: 'EMERGENCY',
        Frame: "/MovieCardPosters/3.png", 
        BigPoster: '/BigPosters/Big3.png', 
        Logo: '/MovieLogos/Logo_3.png',
        Context: "This dramatic portrayal of the Emergency era in India explores Indira Gandhi's leadership, political oppression and the resulting societal upheaval.",
        Release: '2025',
        Category: 'A',
        Type: 'Movie',
        Theme_1: 'Dramas',
    },

    { 
        Name: 'OFFICER',
        Frame: "/MovieCardPosters/4.png", 
        BigPoster: '/BigPosters/Big4.png',
        Logo: '/MovieLogos/Logo_4.png',
        Context: "During a routine case for counterfeit jewelry, a demoted police officer unexpectedly steers his investigation toward a dangerous criminal syndicate.",
        Release: '2025',
        Category: 'A',
        Type: 'Movie',
        Theme_1: 'Thrillers',
        Theme_2: 'Dramas',
    },

    { 
        Name: 'NADAANIYAN',
        Frame: "/MovieCardPosters/5.png", 
        BigPoster: '/BigPosters/Big5.png', 
        Logo: '/MovieLogos/Logo_5.png',
        Context: "When a misunderstanding turns her friends against her, lovable rich girl Pia hires Arjun, a career-focused new student, to pretend to be her boyfriend.",
        Release: '2025',
        Category: 'U/A 13+',
        Type: 'Movie',
        Theme_1: 'Comedies',
        Theme_2: 'Romance',
        NetflixType: '/NetflixType/N_Film.png',
    },

    { 
        Name: 'KHAKEE THE BENGAL CHAPTER',
        Frame: "/MovieCardPosters/6.png", 
        BigPoster: '/BigPosters/Big6.png',
        Logo: '/MovieLogos/Logo_6.png',
        Context: "When upright cop Arjun Maitra takes on Kolkata’s feared don Bagha and his henchmen, he must battle a broken system and navigate bloody gang wars.",
        Release: '2025',
        Category: 'U/A 16+',
        Type: 'Show',
        Theme_1: 'Thrillers',
        Theme_2: 'Dramas',
        NetflixType: '/NetflixType/N_Series.png',
    },

    { 
        Name: 'VIDAAMUYARCHI',
        Frame: "/MovieCardPosters/7.png", 
        BigPoster: '/BigPosters/Big7.png',
        Logo: '/MovieLogos/Logo_7.png',
        Context: "While struggling with his broken marriage, Arjun is pulled into a desperate search for his wife, Kayal, when she goes missing during a road trip.",
        Release: '2025',
        Category: 'U/A 16+',
        Type: 'Movie',
        Theme_1: 'Action',
        Theme_2: 'Thrillers',
        Theme_3: 'Mysteries',
    },

    { 
        Name: 'THANDEL',
        Frame: "/MovieCardPosters/8.png", 
        BigPoster: '/BigPosters/Big8.png',
        Logo: '/MovieLogos/Logo_8.png',
        Context: "Raju, an Indian fisherman, is arrested after accidentally straying into foreign waters and faces a fraught journey home to his beloved Satya.",
        Release: '2025',
        Category: 'U/A 13+',
        Type: 'Movie',
        Theme_1: 'Action',
        Theme_2: 'Romance',
        Theme_3: 'Dramas',
    },

    { 
        Name: 'PUSHPA 2',
        Frame: "/MovieCardPosters/9.png", 
        BigPoster: '/BigPosters/Big9.png',
        Logo: '/MovieLogos/Logo_9.png',
        Context: "As his smuggling empire grows, a brazen Pushpa longs for power and respect on his vengeful journey, while facing old rivals and new.",
        Release: '2025',
        Category: 'U/A 16+',
        Type: 'Movie',
        Theme_1: 'Action',
        Theme_2: 'Dramas',
    },

    { 
        Name: 'DAAKU MAHARAAJ',
        Frame: "/MovieCardPosters/10.png", 
        BigPoster: '/BigPosters/Big10.png',
        Logo: '/MovieLogos/Logo_10.png',
        Context: "When powerful forces threaten a young girl, a fearless man with a criminal past steps in to protect her and the community from danger.",
        Release: '2024',
        Category: 'U/A 16+',
        Type: 'Movie',
        Theme_1: 'Action',
        Theme_2: 'Thrillers',
    },

];
  
export default Movies;
  